### ISSUE TITLE
Changing the length of the CB and UMI

### ISSUE THREAD

**Issue by annajbott** [COMBINE-lab/minnow#2]
Hi,
I'm trying to simulate DropSeq reads. The paper for minnow says the user can specify the UMI and CB length but I can't seem to find an option for this. 

Thanks,
Anna

**Comment by hiraksarkar** [comment]
Thanks for trying out Minnow. Currently we are using 10x based reads therefore we fixed the CB and UMI length. I am adding an option back in the command line and for changing the length. Thanks a lot for pointing it out.

**Comment by annajbott** [comment]
Hi,
Thanks for your reply! I am unable to install it using the git repository due to compiler issues. When are you likely to update the bioconda version?

Thanks a lot!
Anna

**Comment by hiraksarkar** [comment]
Hi, 

The current bioconductor version has some merge conflicts, (there are a ton of changes from the previous version), after pushing the current change, I would try to resolve some. In the mean time, please let me know about the compilation errors you are getting.

**Comment by hiraksarkar** [comment]
Hi Anna, 

I just added `--CBLength` and `--UMILength` options to the minnow. Please let me know if they behave as you expect. Also I am trying to push a release before bioconda. So that you can use the binary. But resolving the compilation would be great. I am sorry that you are having compilation problems.  
--
Hirak

**Comment by annajbott** [comment]
Hi,
So for cmake .. I get:
``` 
>cmake ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
 -pg -g -gstabs -pthread -std=c++11 -W -Wall -Wextra -Wpointer-arith -Wunused -Wwrite-strings -openmp -Wno-unknown-pragmas -Wno-unused-function -O3 
Build system will NOT compile libgff
-- Configuring done
-- Generating done
-- Build files have been written to: /ifs/home/annajb/minnow/build
```
And then for make I get:
```
>make 
Scanning dependencies of target validatelib
[  2%] Building CXX object src/CMakeFiles/validatelib.dir/FASTAParser.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [src/CMakeFiles/validatelib.dir/build.make:63: src/CMakeFiles/validatelib.dir/FASTAParser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:108: src/CMakeFiles/validatelib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I got these error messages running on both mac and linux. 

Cheers,
Anna

**Comment by hiraksarkar** [comment]
Hi Anna, 

As it seems, the gcc version is old. Is it possible to update the gcc/g++ version. `-std=c++11` is 
introduced only after version 4.7. 

Hirak
PS: Did the binary work?

**Comment by hiraksarkar** [comment]
Hi Anna, 

I also resolved the merge conflicts and issued a pull request for the latest version in bioconda 
https://github.com/bioconda/bioconda-recipes/pull/16913
Hopefully it will be available soon. 

--
Hirak

**Comment by annajbott** [comment]
Hi Hirak,
Updated my gcc version to 4.9 but still seem to be getting errors on my mac:
```
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-4.9
-- Check for working C compiler: /usr/local/bin/gcc-4.9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++-4.9
-- Check for working CXX compiler: /usr/local/bin/g++-4.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
 -pg -g -gstabs -pthread -std=c++11 -W -Wall -Wextra -Wpointer-arith -Wunused -Wwrite-strings -openmp -Wno-unknown-pragmas -Wno-unused-function -O3 
Build system will NOT compile libgff
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/annajames-bott/Documents/DPhil/Year_1/Transfer/minnow/build
```

```
make 
Scanning dependencies of target validatelib
[  2%] Building CXX object src/CMakeFiles/validatelib.dir/FASTAParser.cpp.o
/Users/annajames-bott/Documents/DPhil/Year_1/Transfer/minnow/src/FASTAParser.cpp:1:0: error: target system does not support the "stabs" debug format
 #include <cstdio>
 ^
make[2]: *** [src/CMakeFiles/validatelib.dir/FASTAParser.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/validatelib.dir/all] Error 2
make: *** [all] Error 2
```
I am not able to change my compiler on my linux cluster, so I have tested only on my mac.
It could be super easy to fix, I'm am just terrible involving anything regarding C or compilers, sorry!

Thanks,
Anna

**Comment by hiraksarkar** [comment]
Hi Anna, 
A quick fix to the problem in mac is to remove  `--gstab` and `--pg` from line number 20 of 
`CMakeLists.txt`, 
So the line would become simply this.
`set(DEBUG_FLAGS "--g")`
After that please run, within build
```
rm CMakeCache.txt
cmake ..
make
```
Please let me know if that does it.

**Comment by annajbott** [comment]
Brilliant yeah that's worked, thanks! I'll try out the software now cheers.

Anna

**Comment by hiraksarkar** [comment]
Hi Anna, 

Meanwhile I am working on solving the issue with conda compilation. Please let me know if you find any problem/errors. 

--
Hirak

**Comment by hiraksarkar** [comment]
Hi Anna, 

I was wondering if you are facing any more problems. As it's now compilable on mac pulling from github, I think I can iterate easily to make it work, in case you are having any problem running it.

Thanks,
Hirak

**Comment by annajbott** [comment]
Hi Hirak,
Cannot update gcc on my cluster and keep getting sgementation faults on my mac running minnow simulate on splatter-mode. So I guess I have to wait until the conda version is released to be able to use my cluster. 

Thanks,
Anna

**Comment by hiraksarkar** [comment]
Hi Anna, 

Is the mac version giving you seg faults on your machine, if you provide me with the command 
that gives you seg fault, I can work on that to resolve. 

Hirak

**Comment by annajbott** [comment]
Hi,

Output from splatter mode on my mac:
```
> src/minnow simulate --splatter-mode --g2t human_t2g.tsv -m splatter.dir --PCR 5 -r splatter.dir/human_transcriptome.fasta -e 0.001 -o minnow.dir -p 1 --dbg --gfa splatter.dir/human_transcriptome_debruijn.gfa 
Matrix File Name splatter.dir
Reference Fasta splatter.dir/human_transcriptome.fasta
Number of PCR cycles 5
Erorr rate 0.001
Numeber of threads 1
[2019-08-19 10:42:59.182] [minnow-Log] [info] Reading reference sequences ...
replaced 4 non-ACGT nucleotides with random nucleotides
Transcript file is read
[2019-08-19 10:43:02.767] [minnow-Log] [info] Reference sequence is loaded ...
Skipped 0 transcripts because either short or not present in reference 
[2019-08-19 10:43:02.770] [minnow-Log] [info] Number of genes in the txp2gene file: 0
[2019-08-19 10:43:02.770] [minnow-Log] [info] Parsing splatter.dir/quants_mat_cols.txt
[2019-08-19 10:43:02.780] [minnow-Log] [info] 1500 cells are present 
[2019-08-19 10:43:02.780] [minnow-Log] [info] Start parsing Splatter output
[2019-08-19 10:43:02.780] [minnow-Log] [info] Parsing splatter.dir/quants_mat_rows.txt
Segmentation fault: 11
```

Also the splatter matrix I am trying to pass has 1500 genes and 779 cells. So the log message of "1500 cells are present" makes me think maybe the matrix is being read the opposite way round. 

I've also tried alevin mode:

```
src/minnow simulate --alevin-mode --binary --g2t human_t2g.tsv -m alevin --PCR 5 -r splatter.dir/human_transcriptome.fasta -e 0.001 -o minnow.dir -p 1 --dbg --gfa splatter.dir/human_transcriptome_debruijn.gfa 
Matrix File Name alevin
Reference Fasta splatter.dir/human_transcriptome.fasta
Number of PCR cycles 5
Erorr rate 0.001
Numeber of threads 1
[2019-08-19 10:58:53.816] [minnow-Log] [info] Reading reference sequences ...
replaced 4 non-ACGT nucleotides with random nucleotides
Transcript file is read
[2019-08-19 10:58:57.507] [minnow-Log] [info] Reference sequence is loaded ...
[2019-08-19 10:58:57.509] [minnow-Log] [info] The alevin matrix file is in binary mode
Skipped 0 transcripts because either short or not present in reference 
[2019-08-19 10:58:57.511] [minnow-Log] [info] Number of genes in the txp2gene file: 0
[2019-08-19 10:58:57.511] [minnow-Log] [info] Start parsing Alevin
[2019-08-19 10:58:57.511] [minnow-Log] [info] Parsing alevin/quants_mat_cols.txt
[2019-08-19 10:58:57.549] [minnow-Log] [info] Original number of genes: 57627	Number of genes skipped: 57627
[2019-08-19 10:58:57.549] [minnow-Log] [info] Number of genes in the alevin produced files: 0
[2019-08-19 10:58:57.549] [minnow-Log] [info] Parsing alevin/quants_mat_rows.txt
[2019-08-19 10:58:57.552] [minnow-Log] [info] Number of cells in the alevin produced files: 1994
whitelist.txt file does not exist/ or will NOT be used
we need to assume that the rows are 
the whitelisted barcodes 
Start loading segments... 
Saw 815590 contigs in total, unitigMap.size(): 619336
Max contig id 4683369
Starting to load paths 
Done with GFA 
Equivalece class size 619336	trSegmentMap size 0	transcript map size 197385
Done Filtering 
Equivalece class size 513113	trSegmentMap size 196254	transcript map size 197385
 Read GFA file 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul
Abort trap: 6
```

Thanks,
Anna

**Comment by hiraksarkar** [comment]
Hi Anna, 

For the splatter-mode we follow the splatter way of representing the matrix, which means it is gene to cell rather than cell to gene which is alevin way of specifying the matrix. I should come up with a better convention. 

The alevin mode works when we run alevin on the raw read dataset first and then run minnow. 
If possible can you please share the splatter matrix you are getting error with (you can email at hsarkar@cs.stonybrook.edu), or by sharing in a drive.

**Comment by hiraksarkar** [comment]
Hi Anna, 

I just pushed code to catch the splatter gene-to-cell switch. About how we should run minnow with splatter matrix. I should have done a better job explaining it in tutorial, but here is the basic idea, if we don't run alevin, then we depend on the `weibull` distribution to distribute the gene count to candidate isoform counts and as the splatter gene names are sort of not real so we assign gene names on the basis of the uniqueness values. So after git pull if you run this 

```
src/minnow simulate --splatter-mode --CBLength 10 --UMILength 10 --g2t /mnt/scratch6/avi/data/cgat/references/metadata/hg_t2g.tsv -m ../example_data/anna_example_splatter  --PCR 4 -r /mnt/scratch6/avi/data/cgat/references/txome/hg_transcriptome.fasta -e 0.01 -p 10 -o worst --useWeibull --testUniqness --uniq ../data/hg/hg_stranded_gene_uniqueness.txt
```
the t2g files and fasta files are same as what I provide on zenodo. The uniqueness file is uploaded to the github repo itself. 

Thanks

**Comment by annajbott** [comment]
Hi Hirak,
Brilliant cheers I've got simulated reads! I had to use a linux virtual machine to get it to work. My mac was still giving segmentation faults, not sure why. 
Thanks a lot for going through this with me!

Best wishes,
Anna

**Comment by hiraksarkar** [comment]
Hi Anna,

Sad to hear that it did not work for mac, I will try for mac today. Thanks for giving it a try. Your problems also help me to understand that I should re-factor it in a more user-friendly way and write a revised tutorial. 

Thanks

**Comment by annajbott** [comment]
Any update on bioconda release? My virtual machine cannot really handle it for any larger matrices. Thanks

**Comment by annajbott** [comment]
Sorry another question. So I've ran splatter mode with 
```
---useWeibull --testUniqness --uniq data/hg/hg_stranded_gene_uniqueness.txt
```
My splatter matrix has 400 cells, my fastq file has 1600 lines. Am I right in thinking that each cell only has 1 associated read? Is that what the uniq settings do? Sorry to ask but the help only says "matrix file is obtained from running splatter" for many of the splatter related options.
How do I make it so there are more transcripts per cell, as per real single cell data?

Cheers,
Anna

**Comment by annajbott** [comment]
There is numMolFile but then I assume it makes it uniform across every cell?

**Comment by annajbott** [comment]
Fantastic thank you! I will re-run it now

**Comment by hiraksarkar** [comment]
I have also shared a sizable dataset in a google drive. Would you mind if I close this issue and open a new one with the conda version ? 

Hirak
