### ISSUE TITLE
Decoys in README instructions

### ISSUE THREAD

**Issue by baraaorabi** [COMBINE-lab/minnow#23]
In the README file, [when constructing Salmon index](https://github.com/COMBINE-lab/minnow#step-01----build-salmon-index), shouldn't the transcripts file be concatenated by the genome contigs (as done [here](https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/))?

**Comment by hiraksarkar** [comment]
We don't follow the decoy principle of salmon indexing, @DongzeHE can illuminate more. But if you have a specific usecase in mind with respect to minnow I can try to include that.
