### ISSUE TITLE
Setting the number of reads and changing the length of transcript read

### ISSUE THREAD

**Issue by NemanjaVucic90** [COMBINE-lab/minnow#4]
Hello, 
Following the typical example (minimal) to simulate scRNA-seq reads using alevin-mode, I've encountered two issues:
- the output files containing reads are pretty small (less than 200Kb) containing fewer than 1500 reads. Is there a way to set the value for the expected number of reads?
- the length of transcript read in the second fastq file is 100bp which is not compatible with 10x Chromium protocols, is there a way to set a desired length of the transcript reads?

**Comment by hiraksarkar** [comment]
Hi @NemanjaVucic90 , 

Can you please share the command you have used.

**Comment by NemanjaVucic90** [comment]
`minnow simulate --alevin-mode --binary --g2t Homo_sapiens.GRCh38.97.tx2gene.tsv -m /minnow_files/pbmc1k_alevin/alevin -r Homo_sapiens.GRCh38.97.cdna.all.fa.gz --PCR 8 -e 0.001 -p 16 -o test_dir --useWhiteList`

**Comment by hiraksarkar** [comment]
Hi @NemanjaVucic90 ,

Thanks for sharing the command, the PCR cycle decides the total size of the PCR tree and thereby increases the number of reads at the leaves of the tree. We sample the PCR tree in order to create the reads. Nevertheless the PCR cycles of 8 should be more than enough. The next thing that comes to my mind is the molecule content in the matrix to begin with. So it would be great if you can zip the alevin output and share it so that I can reproduce the output. 

Thanks

**Comment by NemanjaVucic90** [comment]
Here's the content of the alevin output directory.

[pbmc1k_alevin_out.zip](https://github.com/COMBINE-lab/minnow/files/3516333/pbmc1k_alevin_out.zip)

**Comment by hiraksarkar** [comment]
Hi @NemanjaVucic90 , 

I am rerunning with the same file and getting far more number of reads. I think there is probably 
a mismatch between the reference sequences names you are using and the reference names that are used. Can you please try the reference files I shared on zenodo and test. In the mean time if you give me the web links of the files then I can try to reproduce the problem. 

Just to remember for running with alevin output directory use the BFH file provided if you don't want to use a bfh file of your own.

**Comment by NemanjaVucic90** [comment]
Hi @hiraksarkar,
Thank you for investing your time into this, really appreciate that. I've used Ensembl GRCh38 release 97 cDNA reference and GTF annotation file to generate tx2gene and run Minnow. Using these files I've also tried to create GFA file with TwoPaCo as you explained, but the de-Bruijn graph output did not seem to be correctly made. Maybe these two issues are related and due to gene and transcript ID labels in Ensembl files which include the dot (ENSG00000164867.1 instead of ENSG00000164867).

**Comment by NemanjaVucic90** [comment]
Hi @hiraksarkar,
just to let you know that I've rerun Minnow with the Ensembl reference and a tx2gene file I've used before and included de-Bruijn graph file from zenodo with the original BFH from alevin run. The size of the fastq files seems to be ok now. Thank you for your time, I'll close this issue now.
