### ISSUE TITLE
demo data of minnow

### ISSUE THREAD

**Issue by yueli8** [COMBINE-lab/minnow#6]
Hello, 

Thank you so much for developing so nice software.

I followed `https://combine-lab.github.io/alevin-tutorial/2019/running-minnow/`.

But where is the data of `transcript.fasta`,`t2g.tsv`,`quants_mat.csv`,`quants_mat_rows.txt`,`quants_mat_cols.txt `?

Thanks in advance for great help!

Best,

Yue

**Comment by hiraksarkar** [comment]
Dear Yue, 

Thanks for trying it out. Apart from providing demo data, I would like to point you out that please use the https://github.com/COMBINE-lab/minnow/tree/refactor branch. 

This new version comes with many features, such as creating your own index 
(which contains the gtf files etc.).  

You can find the most recent demo files [here](https://drive.google.com/drive/folders/1FpycJYus5N3iTbGVDXXxY4Toqvex1tEA?usp=sharing)

After you git clone the `refactor` branch and build it, for running in the splatter more please run,

> minnow simulate --splatter-mode --g2t demo/tx2gene.tsv --inputdir demo/splatter_demo/ --PCR 4 -r demo/gencode.v32.transcripts.fa -e 0.01 -p 2 -o  demo_out --dbg --gfa demo/dbg_gencode_v32.gfa -w demo/737K-august-2016.txt --bfh demo/bfh_gencode_v32.txt --gencode

`demo` is directory that is uploaded in the above link. Please let us know if you face any problem. There are new options added in this version, which extends the general application of minnow. Don't hesitate to post questions if you have any problems. 

Thanks.

**Comment by yueli8** [comment]
Dear, hiraksarkar,

Thank you so much for your quick response!

 This code works perfect!  Thank you again!

Another two questions:

1. This new version comes with many features, such as creating your own index
(which contains the gtf files etc.)

I can not find the `gtf` files int the new version.

2.I understand the meaning of the files `tx2gene.tsv` and `gencode.v32.transcripts.fa`.

 Have you any files to explain the file `dbg_gencode_v32.gfa`, `737K-august-2016.txt`, and `bfh_gencode_v32.txt `?

Where are these files comes from? and What the meaning of these files?

Thank you in advance for your great help! I really appreciated!

Best,

Yue

**Comment by hiraksarkar** [comment]
Dear Yue, 

I mistakenly wrote `gtf` I meant the `gfa` file. Here is a brief description of the files, 

`dbg_gencode_v32.gfa` ~ This is the file with the de-Bruijn graph, that is built on the reference transcriptome fasta file. 

`737K-august-2016.txt` ~ this is a file that contains cell barcodes taken from 10X website. These barcodes are already known. We use them so that our simulated dataset resembles the actual 10X dataset. 

`bfh_gencode_v32.txt` ~ when minnow is run in the `splatter-mode` to make the simulated data realistic, it reads this already existing file from a real run of `alevin`. This file contains a succinct representation of histogram of frequency of different transcripts in different cells. This consolidated file helps minnow to understand how to distribute gene counts to the transcripts that constitute the gene. 

Hope it helps.

**Comment by yueli8** [comment]
Dear hiraksarkar,

Thank you so much for your detail explanation!

Thank you again and `minnow` is really a great software!

Best,

Yue

**Comment by hiraksarkar** [comment]
Dear Yue, 

I am really happy that you liked it. I am always open to suggestions and improving the software. Please don't hesitate to ping me if you want a new functionality or you feel something is not working as it should. 

Best, 
PS : if you find this useful, I would really appreciate if you please star the repo, :)

**Comment by yueli8** [comment]
Dear  hiraksarkar,

Thank you for your message!

1. It is really useful, but how I can `star the repo`?

2. Where these `minnow_demo_gencode_32` data come from? I that possible I have to build by my own?

Thank you again!

Best,

Yue

**Comment by hiraksarkar** [comment]
Dear Yue, 

Minnow works on a count matrix. In splatter mode, the count matrix is present in `splatter_demo` folder. If you looked into the folder, you would see there are three files, 
`quants_mat_cols.txt`  ~ the cell ids, (this file will tell minnow how many cells are to be generated)
`quants_mat.csv` ~ the actual cell to gene count matrix, (check the dimension of the matrix).
`quants_mat_rows.txt` ~ the genes (if can be real name of genes or any arbitrary gene names in which case  minnow will choose some genes to work with.)

I short if you want to use your own simulation, you can keep the other files exactly same and create these three files according to your need. 

I have a slack channel for minnow, [invitation link](https://join.slack.com/t/minnowgroup/shared_invite/enQtOTQ1NzY1MDMwODUwLWEyZDVjM2UzMTE0NDhlYTk5OTBhMzlkZDFhYjk5YTQ3ZTExODk3Mzk1OGFkNTI4YTlkZjU2MDhkOTRkZTIyYjQ) if you want you can join the channel, and that would be more real time, and I will be able to understand what you are exactly trying to do with minnow. 

Hope it helps.

**Comment by yueli8** [comment]
Dear, hiraksarkar,

Thank you so much for your detailed explanation!

I totally understood!

Thank you again!

Best,

Yue

**Comment by hiraksarkar** [comment]
@yueli711 Do you need any more help regarding the issue as you reported? Please feel free to re-open the thread with the question.
