### ISSUE TITLE
fixfasta executable does not respond appropriately to `--help` or `-h`

### ISSUE THREAD

**Issue by ghferrari** [COMBINE-lab/minnow#9]
I've just attempted to build this on Centos 7.6 with GCC 7.3.0 and the resulting `fixfasta` executable does not recognise the `--help` or `-h` parameters.

**Comment by hiraksarkar** [comment]
Hi @ghferrari , 
I hope you are building the `refactor` branch, which is currently a default, please use the `index` command to build the index.

**Comment by ghferrari** [comment]
Sorry, I should have mentioned, this is with release beta_1.5.

**Comment by hiraksarkar** [comment]
Hi, I would strongly suggest to not use the conda version as of now. They are not letting us use the pre-release, so we are going to go with the full release. Until then please use github repo to build it from source. Let me know if you need the binary.

**Comment by ghferrari** [comment]
I did indeed build from source using the latest beta_1.5 release available from this page https://github.com/COMBINE-lab/minnow/releases

**Comment by hiraksarkar** [comment]
Ahh, I see, I should have put a new release, my apologies, can you git pull and build, if it does not work, let me know, I will put the binary here, or issue a release.

**Comment by hiraksarkar** [comment]
@ghferrari  Please try this one https://github.com/COMBINE-lab/minnow/releases/tag/beta_1.6

**Comment by hiraksarkar** [comment]
After building the version you can build a de-bruijn graph with an oneliner 
```
src/minnow index -r <fasta.fa> -k 101 -f 20 --tmpdir tmp -p 10 -o <ind_dir>
```
Here the command line options have the same meaning as described in original twopaco.

**Comment by ghferrari** [comment]
Hi @hiraksarkar , I tried building beta_1.6 but no `fixfasta` executable was built - is it supposed to be there or not with this version?

Also, I don't have a `fasta.fa` file or any other files to test with. Are there some I can download?

**Comment by hiraksarkar** [comment]
@ghferrari The point of fixfasta  was to fix a `fasta file` (that you want to sequence data from) and then produce a `de-bruijn` graph from the fasta file that you already have.

The new version does not need those intermediate steps as they would be called internally. 

About having the proper fasta file, it is determined by the kind of organism you want your single cell experiment to base on. For example if you work with human, you want to have a human fasta file, which can be downloaded from gencode etc.

**Comment by ghferrari** [comment]
Thank you, beta_1.6 builds successfully. I will have to ask a colleague to test it with real data.

Many thanks for your help!

**Comment by hiraksarkar** [comment]
No worries, let me know if you need any help.
